---
title: Parallel MCMC Chains
output: html_document
---

<!---
http://danielturek.github.io/public/parallelMCMC/parallelMCMC
-->

Back to [NIMBLE Vignettes](https://danielturek.github.io/public/nimble_vignettes.html)

\    

The following demonstrates how to execute `nchains` chains of an MCMC using
the `parallel` package.

The samples are then inspected, and optionally each chain can continue
parallel execuation to extend the MCMC run.

\   


```{r, eval = FALSE}
library(nimble)
library(parallel)

code <- nimbleCode({
    mu ~ dnorm(0, 0.001)
    sigma ~ dunif(0, 1000)
    for(i in 1:N) {
        y[i] ~ dnorm(mu, sd = sigma)
    }
})

set.seed(0)
N <- 10
y <- rnorm(N, 4, 2)

constants <- list(N = N)

data <- list(y = y)

initsFunction <- function() {
    list(mu = rnorm(1),
         sigma = runif(1, 0, 10))
}
    
nchains <- 3   ## number of chains
cl <- makeCluster(nchains, timeout = 86400)    ## 1 day
clusterExport(cl, c('code', 'constants', 'data'))

for(i in seq_along(cl)) {
    set.seed(i)
    inits <- initsFunction()
    clusterExport(cl[i], c('inits', 'i'))
}

samplesList1 <- clusterEvalQ(cl, {
    library(nimble)
    Rmodel <- nimbleModel(code, constants, data, inits)
    conf <- configureMCMC(Rmodel)
    Rmcmc <- buildMCMC(conf)
    Cmodel <- compileNimble(Rmodel)
    Cmcmc <- compileNimble(Rmcmc, project = Rmodel)
    set.seed(i)
    samples <- runMCMC(Cmcmc, 10000)
    return(samples)
})

names(samplesList1) <- paste0('chain', 1:nchains)
```

```{r echo = FALSE, eval = FALSE}
save(samplesList1, file = '~/github/public/parallelMCMC/SL1.RData')
```

```{r echo = FALSE}
load('~/github/public/parallelMCMC/SL1.RData')
```

\  

Inspect the samples in `samplesList1`:


```{r, fig.width = 6, fig.height = 3}
lapply(samplesList1, dim)

library(basicMCMCplots)
chainsPlot(samplesList1)
```

\  

Now continue running each MCMC chain for an additional 20000 samples:

```{r eval = FALSE}
samplesList2 <- clusterEvalQ(cl, {
    Cmcmc$run(20000, reset = FALSE)
    samples <- as.matrix(Cmcmc$mvSamples)
    return(samples)
})

names(samplesList2) <- paste0('chain', 1:nchains)
```

```{r echo = FALSE, eval = FALSE}
save(samplesList2, file = '~/github/public/parallelMCMC/SL2.RData')
```

```{r echo = FALSE}
load('~/github/public/parallelMCMC/SL2.RData')
```

```{r }
lapply(samplesList2, dim)
```


\  

\  

\  

\  

\  

\  

\  

\  

\  

\  

\  

\  

\  

\  

