---
title: NIMBLE MCMC Vignettes
author: Daniel Turek
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

<!---
danielturek.github.io/public/nimble_vignettes.html
<a href="URL_GOES_HERE" target="_blank">HYPERLINK_TEXT_OPENS_IN_NEW_TAB</a>
-->

\   

## MCMC Algorithms

<a href="http://danielturek.github.io/public/MCMCsuite/MCMC_suite_example.html" target="_blank">MCMC Suite Example</a> - An example of using NIMBLE's MCMC Suite to run BUGS, JAGS, or different NIMBLE MCMCs.

<a href="http://danielturek.github.io/public/avoidRecompile/avoidRecompileMCMC.html" target="_blank">Avoid Recompiling an MCMC</a> - How to avoid re-compiling an MCMC algorithm,when using different MCMC sampling combinations for the same model.

<a href="http://danielturek.github.io/public/restartingMCMC/restartingMCMC.html" target="_blank">Restarting NIMBLE MCMC</a> - How to continue an MCMC algorithm from where it left off, after restarting an R session.

<a href="https://danielturek.github.io/nngp/analysis/index.html" target="_blank">Gaussian Process and NNGP Models with MCMC</a> - How to fit Gaussian Process (GP) and Nearest Neighbor Gaussian Process (NNGP) models with NIMBLE's MCMC.

<a href="https://danielturek.github.io/public/saveMCMCstate/saveMCMCstate.html" target="_blank">Saving Model and MCMC State</a> - How to save the state of a model object and associated MCMC algorithm, allowing you to restart R, reload the state into a new model and MCMC, and resume the MCMC sampling where it left off.

<a href="http://danielturek.github.io/public/parallelMCMC/parallelMCMC.html" target="_blank">Parallel MCMC Chains</a> - How to execute parallel MCMC chains using the `parallel` package, and also to optionally continue running each MCMC chain after assessing convergence.





\   

## MCMC Samplers

<a href="http://danielturek.github.io/public/recordingSamples/recordingSamples.html" target="_blank">Recording Sampler Pre- and Post-Update Values</a> - How to modify NIMBLE MCMC samplers, so they internally record parameter values before and after updating them.  This can be useful for post-analysis of sampler performance.

<a href="http://danielturek.github.io/public/samplerTimings/samplerTimingsExample.html" target="_blank">Timing Individual MCMC Samplers</a> - An example of how to measure the runtime of each individual MCMC sampler.  This can be useful for post-analysis of sampler performance.

<a href="http://danielturek.github.io/public/addSamplerConjugate/addSamplerConjugate.html" target="_blank">Adding a Conjugate Sampler</a> - How to manually add a conjugate sampler to an MCMC configuration object.

<a href="http://danielturek.github.io/public/RW_record/RW_record.html" target="_blank">Recording Sampler Tuning Parameters</a> - Writing the RW sampler so that it records (and you can access) the scale history and acceptance rate history.

<a href="http://danielturek.github.io/public/samplerVariables/samplerVariables.html" target="_blank">Sampler State Variables</a> - How to extract and set the "state" variables, stored internally in MCMC sampling algorithms.

<a href="http://danielturek.github.io/public/toggleSamplers/toggleSamplers.html" target="_blank">Toggling MCMC Samplers On/Off</a> - How to modify MCMC samplers so they can be toggled on or off for different MCMC runs or datasets.


\   

## Other

<a href="https://github.com/nimble-dev/nimble/wiki/MCMC-Style-Guide" target="_blank">MCMC Style Guide</a> - The NIMBLE MCMC Team welcomes external contributions of sampling algorithms, new features, or otherwise.  Please see this guide regarding MCMC code formatting.

<a href="http://danielturek.github.io/public/codeSubstitution/demo.html" target="_blank">Code Substitution</a> - How to manipulate `code` objects in R, including use of the `substitute` and `eval` functions.

<a href="http://danielturek.github.io/public/jags_block_adaptation/jags_block_adaptation.html" target="_blank">JAGS Block Sampling Adaptation</a> - Describes the algorithm underlying JAGS' block sampler adaptation scheme.

<a href="http://danielturek.github.io/public/sparseMatrixCall/sparseMatrixCall.html" target="_blank">Sparse Matrix Calls</a> - Demonstrating how to use sparse matrix operations from the `Matrix` package inside compiled NIMBLE functions and models.

<a href="https://nature.berkeley.edu/~pdevalpine/SCR_NIMBLE_ideas/SCR_NIMBLE_ideas.html" target="_blank">Spatial Capture-Recapture (SCR) Ideas</a> - Exploring methods for improving sampling efficiency of spatially-explicit spatial capture-recapture (SCR) models using NIMBLE.

<!--
<a href="http://danielturek.github.io/public/scr/wolverine_example.html" target="_blank">Spatial Capture-Recapture (SCR) Wolverine Example</a> - Working example of Wolverine model, as in "Efficient MCMC for Spatial Capture-Recapture Models" (Turek *et al*, *submitted*).
-->




\   

\   

\   

\   

\   

\   

